"gcp_svc_key" = "./iactutorial-467611-eb47ffb11d64.json"
"gcp_project_id" = "iactutorial-467611"
"gcp_region" = "us-central1"
"bucket_name" = "seedwak-bearblog-homepage"
"bucket_location" = "US-CENTRAL1"
